"""Added test field to the Task model

Revision ID: 6a9a0e8192fe
Revises: a4a625b47bce
Create Date: 2025-06-17 18:21:49.978321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a9a0e8192fe'
down_revision: Union[str, Sequence[str], None] = 'a4a625b47bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('test_field', sa.String(), nullable=True, server_default='test field'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'test_field')
    # ### end Alembic commands ###
